### ISSUE TITLE
BUG - date_add does not exist

### ISSUE THREAD

**Issue by peter-dimov** [fivetran/dbt_stripe#22]
**Are you a current Fivetran customer?** 

Peter, Humi :)

**Describe the bug**

Might just be me misusing but:

On model stripe__balance_transactions getting error:

`Postgres error: function pg_catalog.date_add("unknown", integer, timestamp with time zone) does not exist
`

Weird because dbt_utils was properly installed 

```
Installing dbt-labs/dbt_utils@0.7.4
  Installed from version 0.7.4
  Up to date!
```

**Steps to reproduce**
1. Add fivetran/stripe version 0.5.1 to packages.yml
2. dbt deps
3. dbt run --models stripe

**Expected behavior**

**Project variables configuration**

```
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '0.20.2'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
    stripe_schema: landing_stripe
    stripe_database: warehouse
    stripe_timezone: "America/Toronto"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
      # Applies to all files under models/example/
      example:
          materialized: view
  stripe:
    +schema: _stripe
  stripe_source:
    +schema: _stripe_source

```

**Package Version**

```packages:
  - package: fivetran/stripe_source
    version: 0.4.4
  - package: fivetran/stripe
    version: 0.5.1
```

**Warehouse**

 
- [ ] BigQuery
- [x] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 

Need to get solved by EOW
**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
